name: Build + Format
# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the $default-branch branch
    push:
        # branches: [ $default-branch ]
        # branches: [ $default-branch ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
            contents: write

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - run: echo 'Build Monorepo 🐌';

            - name: Checkout 🛎️
              uses: actions/checkout@v3

            - name: Setup Node.js environment 🛎️
              uses: actions/setup-node@v3.8.1
              with:
                  node-version: 18.7.0

            - name: Install pnpm 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
              run: |
                  npm install -g pnpm
                  pnpm install

            - name: BUILD ALL PACKAGES
              run: |
                  pnpm run build && pnpm run fix && pnpm run check
                  git status

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: 'style(root): formatted by bot'
