name: Release

on:
  push:
    branches:
      - development

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment 🛎️
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18.7.0'

      - name: Install pnpm 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install -g pnpm
          pnpm install

      - name: BUILD ALL PACKAGES
        run: |
          pnpm run build && pnpm run fix && pnpm run check
          git status
          git branch
          pnpm -r run prerelease

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: commited by a bot'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          commit: "chore: this commit was g created by changesets"
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
